### ISSUE TITLE
High Severity vulnerability

### ISSUE THREAD

**Issue by massinlaaouaj** [timothypholmes/startup-page#36]
Hi,

when I execute "npm install", your project I get this output.
![image](https://user-images.githubusercontent.com/48721794/175276064-c3af8705-8bbb-43e7-990e-f9f15d5e610d.png)

npm audit:
![image](https://user-images.githubusercontent.com/48721794/175275273-32f40f64-50f4-4d39-bb4f-7f4f614af2ea.png)

npm audit fix:
![image](https://user-images.githubusercontent.com/48721794/175276260-9aa0be02-6ea5-430a-9b19-ffc283444332.png)

Any idea to fix it?

Thanks!

**Comment by timothypholmes** [comment]
Moving this to closed as I can not reproduce. I have spent some time recently on this project again and I believe this is fixed. If you'd like retry to build the project and open a new issue if anything arises.
