### ISSUE TITLE
start-page@0.1.0 build: `vite build` error

### ISSUE THREAD

**Issue by massinlaaouaj** [timothypholmes/startup-page#37]
Hi any idea, what's the solution of this error? Thanks!

npm run build:
![image](https://user-images.githubusercontent.com/48721794/175278634-4c431a22-2018-4a90-b092-ec209f946af0.png)

log error:
[00_debug-node.log](https://github.com/timothypholmes/startup-page/files/8966340/00_debug-node.log)

**Comment by timothypholmes** [comment]
Moving this to closed as I can not reproduce. I have spent some time recently on this project again and I believe this is fixed. If you'd like retry to build the project and open a new issue if anything arises.
