### ISSUE TITLE
Deploying Quetion

### ISSUE THREAD

**Issue by Metastem** [timothypholmes/startup-page#53]
Any instruction about deploying on vercel?

**Comment by timothypholmes** [comment]
@Metastem 

I have been recently working on this project again and have added a lot. With that being said,I have tried to deploy this on vercel and it seems like it will work just fine. 

Setup the site like:
<img width="1680" alt="Screenshot 2023-01-02 at 12 09 44 PM" src="https://user-images.githubusercontent.com/20340720/210278539-71dea1f8-7338-4637-bf3c-8b3c2af2afce.png">

Where the framework is vite. Then for the build use:

<img width="983" alt="Screenshot 2023-01-02 at 3 17 29 PM" src="https://user-images.githubusercontent.com/20340720/210278605-a6458ff0-bc04-4eed-96ae-9369bbfd0178.png">

npm run build:vercel

This should give you a successful build as shown below. 

<img width="1635" alt="Screenshot 2023-01-02 at 3 18 13 PM" src="https://user-images.githubusercontent.com/20340720/210278647-2460db1a-6d7b-42bd-9eb3-243d28c5112d.png">

You can see the site here:

https://vercel.com/timothypholmes/startup-page/TacfE5Az4sjnYvp9woFUS3c49QVC

Another note: I have set this site up to run on GitHub pages. So you should be able to deploy to vercel or GitHub pages.
